<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-19 01:45
=======
# Generated by Django 5.2 on 2025-04-18 11:07
>>>>>>> 803e4e476812aec0875260d05ff503d512c43571

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
<<<<<<< HEAD
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> 803e4e476812aec0875260d05ff503d512c43571
            ],
        ),
    ]
