name: Django CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: testsecretkey

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Override DB settings for CI (use SQLite)
        run: |
          echo "DATABASE_URL=sqlite:///db.sqlite3" >> $GITHUB_ENV

      - name: Run migrations
        run: python manage.py migrate

      - name: Run only the create blog post test
        run: python manage.py test blog.tests.BlogPostCreateViewTestCase

      - name: Run tests
        run: python manage.py test
